source 'https://rubygems.org'

gem 'builder',                      '~> 3.2.0'
gem 'nokogiri',                     '~> 1.6.6'
gem 'middleman',                    '~> 3.3.0'
gem 'middleman-blog',               '~> 3.5.0'
gem 'middleman-deploy',             '~> 1.0.0'
gem 'bootstrap-sass',               '~> 3.3.4'
gem 'font-awesome-middleman',       '~> 4.2.0'
gem 'middleman-google-analytics',   '~> 1.1.0'
